# Generated by Django 5.0.6 on 2024-05-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='farther_name',
            field=models.CharField(max_length=20),
        ),
    ]
