# Generated by Django 5.0.6 on 2024-05-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_app', '0002_student_farther_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('father_name', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='farther_name',
            field=models.CharField(default='Rahim', max_length=20),
        ),
    ]
